language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - npm install yo
  - if [ "$currentfolder" != 'generator-restify' ]; then cd .. && eval "mv $currentfolder generator-restify" && cd generator-restify; fi

